AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  warmane-pvp-analytics

  Sample SAM Template for warmane-pvp-analytics

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CrawlerTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: crawl_trigger.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          TARGET_FUNCTION: !GetAtt CrawlerFunction.Arn
      Timeout: 60 # reduce this later
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !GetAtt CrawlerFunction.Arn
      Events:
        CrawlerTrigger:
          Type: Api
          Properties:
            Path: /crawl
            Method: post

  CrawlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: crawl.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Timeout: 60
      Environment:
        Variables:
          TABLE_NAME: !Select [1, !Split ['/', !GetAtt MatchesTable.Arn]] 
      Policies:
        - Statement:
          Effect: Allow
          Action: "*"
          Resource: !GetAtt MatchesTable.Arn


  MatchesTable:
    Type: AWS::Serverless::SimpleTable


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
