openapi: 3.0.0
info:
  title: Example API
  description: This is an example API
  version: 1.0.0
paths:
  /hello:
    get:
      x-amazon-apigateway-integration:
        httpMethod: GET
        payloadFormatVersion: "1.0"
        type: HTTP_PROXY
        uri: "https://ip-ranges.amazonaws.com/ip-ranges.json"
