name: Continuous Deployment
on: [push]
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: test
        run: npm install

      - name: prettier
        run: npm run prettier

      - name: test
        run: npm test

      - name: build
        run: npm run build

      - name: add node_modules
        run: cp -r node_modules build/

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
          retention-days: 5


  terraform:
    needs: test_and_build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure
    steps:
      - name: download build output
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/v2' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
