name: Continuous Deployment
on: [push]
jobs:
  test_build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: npm install

      - name: prettier
        run: npm run prettier

      - name: test
        run: npm test

      - name: build
        run: npm run build

      - name: copy node_modules
        run: cp -r node_modules build

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: terraform format
        id: fmt
        run: |
          cd infrastructure
          terraform fmt -check

      - name: terraform init
        id: init
        run: |
          cd infrastructure
          terraform init

      - name: terraform validate
        id: validate
        run: |
          cd infrastructure
          terraform validate -no-color

      - name: debug
        run: |
          cd infrastructure
          pwd
          ls ../build
          tree
          tree ../build

      - name: terraform plan
        id: plan
        run: |
          cd infrastructure
          terraform plan -no-color -input=false

      - name: terraform apply
        if: github.ref == 'refs/heads/v2' && github.event_name == 'push'
        run: |
          cd infrastructure
          terraform apply -auto-approve -input=false
